language: python
python: 3.3

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pep8
  - TOXENV=py2pep8
  - TOXENV=docs

before_install:
  - "if [[ $TOXENV == 'py34' ]]; then sudo apt-get update; fi"
  - "if [[ $TOXENV == 'py34' ]]; then sudo apt-get install python3.4 python3.4-dev; fi"

install: pip install tox

script: tox

notifications:
  irc:
    channels:
      - "irc.freenode.org#caremad"
    use_notice: true
    skip_join: true
